rollback version of Bitwarden CLI to old version that doesn't have error
 Error: error:25066067:DSO support routines:dlfcn_load:could not load the shared library